### ISSUE TITLE
Code snippet generation for the CLI SDK & avail them on Graph Explorer & Docs

### ISSUE THREAD

**Issue by CarolKigoonya** [microsoftgraph/msgraph-cli#179]
Generate code snippets  & avail them: 

- [x] Code snippet language generator in DevX API #223 
- [ ] Code snippets availability on GE - add supported language #221 
- [ ] Code snippets availability on docs - add supported language #222

**Comment by baywet** [comment]
@CarolKigoonya would you mind running a comparative analysis between public documentation platforms that have shell snippets. This would be especially helpful for aspects like "how do we escape JSON payloads that need to be passed to the CLI?" (like updating users)
