### ISSUE TITLE
[Tracking] Engineering Cleanup

### ISSUE THREAD

**Issue by ddyett** [microsoftgraph/msgraph-cli#51]
- [x] Update to System.CommandLine  v2.0.0-beta3.22114.1
- [x] Update to System.CommandLine.Hosting v0.4.0-alpha.22114.1
- [x] Update Kiota version (discriminator changes in parsers & models)
